server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    username: "root"
    password: "root"
    url: jdbc:mysql://localhost:3308/my_test?serverTimezone=GMT&uname=root&upwd=root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:sql/*.sql
      data-locations:
        - classpath*:sql/data/*.sql
  redis:
    port: 6379
    host: localhost
    timeout: 5000
  mail:
    host: smtp.qq.com
    username: 1053870367@qq.com
    password: iosoehmegqdlbeih
    protocol: smtps
    default-encoding: UTF-8


mybatis-plus:
  type-aliases-package: com.example.api.Pojo.User
  mapper-locations: classpath:mapper/*.xml


dubbo:
  application:
    name: provider
    owner: Shawn
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20881

rocketmq:
  name-server: localhost:9876
  consumer:
    group: consumer









